CREATE TABLE KOREA 
(
        PLAYER_NUM NUMBER PRIMARY KEY,
        PLAYER_NAME VARCHAR2(100) NOT NULL,
        PLAYER_AGE NUMBER NOT NULL,
        height VARCHAR2(100),
        MAIN_FOOT VARCHAR2(20),
        POSITION VARCHAR2(100)
);
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('26', '오현규', '23', '183cm', 'RIGHT', 'FW');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('25', '정우영', '25', '180cm', 'RIGHT', 'FW');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('9', '조규성', '26', '189cm', 'RIGHT', 'FW');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('16', '황의조', '32', '183cm', 'RIGHT', 'FW');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('22', '권창훈', '30', '174cm', 'LEFT', 'MF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('17', '나상호', '28', '173cm', 'RIGHT', 'MF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('8', '백승호', '27', '182cm', 'RIGHT', 'MF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('13', '손준호', '32', '178cm', 'RIGHT', 'MF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('7', '손흥민', '32', '183cm', 'RIGHT', 'MF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('24', '송민규', '25', '179cm', 'RIGHT', 'MF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('18', '이강인', '23', '173cm', 'LEFT', 'MF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('10', '이재성', '32', '180cm', 'LEFT', 'MF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('5', '정우영', '34', '186cm', 'RIGHT', 'MF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('6', '황인범', '28', '177cm', 'RIGHT', 'MF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('20', '권경원', '32', '188cm', 'LEFT', 'DF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('15', '김문환', '29', '173cm', 'RIGHT', 'DF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('4', '김민재', '28', '190cm', 'RIGHT', 'DF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('19', '김영권', '34', '186cm', 'LEFT', 'DF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('3', '김진수', '32', '177cm', 'LEFT', 'DF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('23', '김태환', '35', '177cm', 'RIGHT', 'DF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('2', '이기제', '33', '176cm', 'LEFT', 'DF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('14', '조유민', '28', '182cm', 'RIGGT', 'DF');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('1', '김승규', '34', '187cm', 'RIGHT', 'GK');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('12', '송범근', '27', '194cm', 'RIGHT', 'GK');
INSERT INTO KOREA (PLAYER_NUM, PLAYER_NAME, PLAYER_AGE, HEIGHT, MAIN_FOOT, POSITION) VALUES ('21', '조현우', '33', '189cm', 'RIGHT', 'GK');










SELECT * FROM KOREA ORDER BY 1;

DELETE FROM KOREA;
ROLLBACK;
COMMIT; 